// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWD9nDzAwfcMnzrefmh9k8FMvDW-pA8bc',
    appId: '1:264972659621:web:a0e6b8f9215369af63d64c',
    messagingSenderId: '264972659621',
    projectId: 'buildxinfo-6c46a',
    authDomain: 'buildxinfo-6c46a.firebaseapp.com',
    storageBucket: 'buildxinfo-6c46a.firebasestorage.app',
    measurementId: 'G-HKCNKXJY6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2ppEaComaq_KB3RJ-naF8oAGDurGbX-A',
    appId: '1:264972659621:android:988a480e66d7115b63d64c',
    messagingSenderId: '264972659621',
    projectId: 'buildxinfo-6c46a',
    storageBucket: 'buildxinfo-6c46a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWD9nDzAwfcMnzrefmh9k8FMvDW-pA8bc',
    appId: '1:264972659621:web:347b0032d27773ca63d64c',
    messagingSenderId: '264972659621',
    projectId: 'buildxinfo-6c46a',
    authDomain: 'buildxinfo-6c46a.firebaseapp.com',
    storageBucket: 'buildxinfo-6c46a.firebasestorage.app',
    measurementId: 'G-99CYZT3W45',
  );
}
